name: Node.js Package (NPM)

on:
    workflow_dispatch:
    push:

jobs:
    publish:
        uses: Bracketed/Workflows/.github/workflows/Package-Publish.yml@main
        permissions:
            contents: write
            id-token: write
            actions: write
        with:
            project-name: '@bracketed/typescript-config'
            checkout-ref: master
            build: false
        secrets:
            BRSFTWORKS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            NODE_AUTH_TOKEN: ${{secrets.NODE_PUBLISH}}
